version: "3"

services:
  node:
    build: .
    container_name: node
    restart: always
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    networks:
      - tradeNetwork

  mysql:
    image: mysql:5.7
    container_name: mysqldb
    hostname: mysql
    restart: always
    tty: true
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cotacoes
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
      - 33060:33060
      - 33061:33061
    networks:
      - tradeNetwork

networks:
  tradeNetwork:
    driver: bridge
